### ISSUE TITLE
Дополнительный функционал

### ISSUE THREAD

**Issue by VideoSar64** [0-6-1-7/rosreestr#1]
Добрый день. При сборе инфрмации по кадастровым номерам хотелось бы чтобы еще собиралась "Площадь ОКС'а:". Возможно ли это реализовать?

**Comment by 0-6-1-7** [comment]
Да, сделаю в течение нескольких дней.

вс, 11 окт. 2020 г. в 13:17, VideoSar64 <notifications@github.com>:

**Comment by VideoSar64** [comment]
Супер. Буду признателен.

**Comment by 0-6-1-7** [comment]
1. Добавил площадь ОКС и дату обновления информации.
2. Изменил обработку даты перехода прав собственности - на выходе должно
быть меньше мусора.

Пока проверил только на небольшом массиве кадастровых номеров, так что если
будут проблемы или вопросы - пишите.

вс, 11 окт. 2020 г. в 18:39, VideoSar64 <notifications@github.com>:
