### ISSUE TITLE
Ошибка при поиске по кадастровым номерам единых землепользований

### ISSUE THREAD

**Issue by vassspaul** [0-6-1-7/rosreestr#10]
При поиске по кадастровым номерам единых землепользований (например, 39:01:000000:311 или 39:11:000000:161) появляется ошибка:

`произошло исключение в get_info_kn
При выполнении возникло исключение <class 'selenium.common.exceptions.ElementClickInterceptedException'>
        описание:       Message: element click intercepted: Element <div class="rros-ui-lib-table__row" data-test-id="row-1" role="row" style="display: flex; flex: 1 0 auto; min-width: 530px;">...</div> is not clickable at point (456, 568). Other element would receive the click: <div class="rros-ui-lib-table__cell" data-test-id="cell-0" role="cell" style="box-sizing: border-box; flex: 150 0 auto; min-width: 150px; width: 150px; display: flex; justify-content: flex-start; max-width: 2000px; overflow-wrap: break-word;">...</div>`

**Comment by 0-6-1-7** [comment]
Добрый день.
У меня не появляется такая ошибка, но подобные объекты действительно обрабатывались неправильно.
Исправил get_info.py.

**Comment by vassspaul** [comment]
Да, обработка единых землепользований теперь осуществляется корректно.
Спасибо!
