### ISSUE TITLE
Подскажите куда EGRN downloader скачивает выписки?

### ISSUE THREAD

**Issue by Bengan77753** [0-6-1-7/rosreestr#11]
Собственно, запустил EGRN downloader v3.3. Пишет все успешно. В файле dn.xlsx все как надо. А где сами выписки не найду никак.

**Comment by 0-6-1-7** [comment]
Скачанные выписки сохраняются в папку загрузок по умолчанию.
![image](https://user-images.githubusercontent.com/60964734/162713887-95e0e0f1-39c4-4105-968d-defd1b631bd2.png)
В последнее время  ФГИС ЕГРН работает отвратительно - приходится по несколько минут ждать загрузку каждого файла.

**Comment by Bengan77753** [comment]
Так и подумал. Странно. Файлов там нет. Ошибок никаких не выдает

**Comment by 0-6-1-7** [comment]
Посмотрите, что происходит в Хроме: если фгис долго отдаёт файл, то в Хроме остаётся открытой пустая вкладка - у меня в пятницу по 15 минут они висели пока скачались. В основном такое происходит когда скачиваешь подряд много ответов.

**Comment by Bengan77753** [comment]
Ок. Просто никак не придут выписки которые на пробу заказал.

**Comment by 0-6-1-7** [comment]
А если руками проверить - какой статус заявки? С 11 апреля ФГИС ЕГРН почти не работает - заявки принимает, но не отрабатывает.
![image](https://user-images.githubusercontent.com/60964734/163673524-dcd6e2d6-494f-4342-98a6-754e91207518.png)

**Comment by Bengan77753** [comment]
Странно, но не скачивает( Приложил видео работы и скрин с настройкой пути для сохранения в Google Chrome
![2022-04-18_121825](https://user-images.githubusercontent.com/65654105/163787202-6e4866f4-16ab-4d03-8e83-932d9e3311f2.png)
https://disk.yandex.ru/d/S_6IQZ1yo4RccA

**Comment by 0-6-1-7** [comment]
Сделайте такой же скрин, как в моём ответе выше.
По ссылке "Ничего не найдено"

**Comment by Bengan77753** [comment]
https://disk.yandex.ru/i/9mCiLK73hsMZ-w

**Comment by 0-6-1-7** [comment]
Ок, понял. По датам пока не работает - у меня была какая-то причина отключить загрузку по датам, уже не помню зачем.
dndx работает нормально.
С датами разберусь в течение недели.

**Comment by Bengan77753** [comment]
Угу. Увидел. Работает. Спасибо)
