### ISSUE TITLE
Предложение по улучшению

### ISSUE THREAD

**Issue by Listlex** [0-6-1-7/rosreestr#2]
Можете прикрутить в бот для запроса выписок? Чтобы он сам подставлял данные из списка. Типа заполнили список, запустили бот, если ошибка, то бот запускается заново, а список уже подставляет с изменениями.

**Comment by 0-6-1-7** [comment]
Все идеи, которые у меня были, разбиились о реальность. А новых пока нет.
Так что в ближайших планах этого нет.

вт, 13 окт. 2020 г. в 15:30, Listlex <notifications@github.com>:

**Comment by 0-6-1-7** [comment]
Автобот (O_O) находится на стадии тестирования. Вероятно, в течение недели выложу. Не уверен насчёт лицензии - вероятно, будет с ограничениями на использование... Ну, вы понимаете.

**Comment by mishkyn-Mms** [comment]
Согласен, что было бы супер, если можно было подставлять в поиск только нужные «кадастровые Номера» и «город». На основании этих двух параметров можно и заказывать выписки.
Полагаю что логика такая же как при авторизации , с учетом шага назад на «изменить запрос»?

**Comment by 0-6-1-7** [comment]
Полностью автоматический бот готов и находится на тестировании. По принципу "1 список = 1 регион".
На этом пока заморожу изменения и займусь загружальщиком запросов - там много чего можно улучшить.

**Comment by mishkyn-Mms** [comment]
У меня не работает только Ваш бот "поиск кадастровых номеров по адресу". Почему-то не подгружает данные из excel-файла, соответственно не читает. Записывает пустой список.

**Comment by 0-6-1-7** [comment]
Пришлите оригинал своего списка KNaddr.xlsx мне на почту 0617@bk.ru

ср, 21 окт. 2020 г. в 10:36, mishkyn-Mms <notifications@github.com>:

**Comment by tatikoma** [comment]
Я прошу прощения, но есть скрипт для запрашивания по списку. Вариант альтернативный, без браузера.
https://github.com/Tatikoma/rosreestr-ownership-parser

Кажется мы примерно в одно время всё это разрабатывали, мой репозиторий чуть постарше =) Предлагаю дружить.

**Comment by 0-6-1-7** [comment]
Ну, у вас там настоящее программирование, а не конструкт из навоза и соломы
как уменя.

пт, 6 нояб. 2020 г. в 00:47, Andrey Ilinskiy <notifications@github.com>:

**Comment by 0-6-1-7** [comment]
Скажите, вы как-нибудь боретесь с выписками, застрявшими в статусе "В
работе"?
Если не против, лучше в почту 0617@bk.ru

пт, 6 нояб. 2020 г. в 00:47, Andrey Ilinskiy <notifications@github.com>:
