### ISSUE TITLE
Ошибка в боте.

### ISSUE THREAD

**Issue by Listlex** [0-6-1-7/rosreestr#6]
Пишет "Сайт Росреестра работает, страница авторизации загружена нормально.
Нет ключа доступа. Дальнейшая работа без ключа невозможна."

, хотя ключ есть. Что можно сделать?
![image](https://user-images.githubusercontent.com/72799112/122007594-c0621380-cdc0-11eb-9a0e-cf8fa9905670.png)

**Comment by 0-6-1-7** [comment]
Добрый день.

Ошибка может возникнуть в случаях:
1. Нет нужного файла или нет доступа к нему - убедитесь, что файл называется именно auth.txt.
2. Первые 36 символов первой строки файла не выглядят как ключ.

**Comment by Listlex** [comment]
1. Файл ключа имя правильно и находится вместе с файлом бота.
2. Если удалить в коде [:36] то ключ вставляется но впереди ставит знаки п»ї

**Comment by AlkashIrk** [comment]
> 1. Файл ключа имя правильно и находится вместе с файлом бота.
> 2. Если удалить в коде [:36] то ключ вставляется но впереди ставит знаки п»ї

99% что проблема в файле.

Попробуйте открыть файл в notepad++
Предварительно настроив отображение всех символов.

Меню **Вид** -> **Отображение символов** -> **Отображать все символы**

![image](https://user-images.githubusercontent.com/46029209/122023268-0d99b180-cdd0-11eb-8468-ec0d4dc14589.png)

**Comment by 0-6-1-7** [comment]
> 1. Файл ключа имя правильно и находится вместе с файлом бота.
> 2. Если удалить в коде [:36] то ключ вставляется но впереди ставит знаки п»ї

Запустите скрипт TestAuthKeyFile.py
Что он пишет?
https://github.com/0-6-1-7/rosreestr/blob/master/EGRN%20bot%20v.3.3/TestAuthKeyFile.py

**Comment by Listlex** [comment]
Скрипт пишет:
Файл имеет правильное имя и доустпен для чтения, прочитана первая строка, всё ОК.
Ошибка, ключ найден с позиции 3
Удалил файл auth.txt и скопировал из старой версии бота. Все заработало.
Файл ключа открывал через notepad++  c отображением всех символов, но кроме ключа никаких лишних символов не было.
