### ISSUE TITLE
Ошибка при сборе данный по кадастровым номерам

### ISSUE THREAD

**Issue by VideoSar64** [0-6-1-7/rosreestr#7]
![image](https://user-images.githubusercontent.com/4356514/135728444-5e35407f-d2ab-4d55-97bb-804fb9a74d4d.png)

**Comment by 0-6-1-7** [comment]
Увы, скорее всего, больше мои скрипты работать не будут - сайт обновился, появилась дикая капча на каждое действие.

**Comment by VideoSar64** [comment]
жаль, капчу не увидел новую. только что они убрали в справочнике. мне по сути полезен именно он был. чтобы собрать в табличный вид данные по кадастровому номеру.

**Comment by 0-6-1-7** [comment]
Я теперь вообще не понимаю как этим пользоваться.

**Comment by VideoSar64** [comment]
сейчас страница со справочной информацией вообще кидает на страницу запроса ФГИС. видимо опять в выходные чинить сайт надумали. подождем понедельника. может удастся подстроиться

**Comment by 0-6-1-7** [comment]
С главной страницы можно зайти на "информация онлайн", но там ужос. Надеюсь, они хотя бы ФГИС ЕГРН не сломают ближайшую неделю.

**Comment by VideoSar64** [comment]
господи, что это??? жесть какая-то. как это развидеть))))

**Comment by mishkyn-Mms** [comment]
Эта каптча вроде не совсем ужасна .
![image](https://user-images.githubusercontent.com/73203411/135729630-76fb4a82-83c8-4318-aae8-9a0d93b4fac4.jpeg)

**Comment by 0-6-1-7** [comment]
Опять доступна страница по старому адресу https://rosreestr.gov.ru/wps/portal/online_request
А на новой - я понимаю как этим пользоваться. Возможно, нужно просто подождать немного.


А, не, недоступна. Это у меня какие-то флэшбэки. Печаль.

**Comment by VideoSar64** [comment]
есть сходство со старой., но не понятно как теперь найти все помещения в многоквартирном доме например. сейчас при поиске выдает только кадастр здания. а вот как собрать все помещения внутри него пока вопрос

**Comment by VideoSar64** [comment]
капча побеждена. единственное условие войти под госуслугами.
![image](https://user-images.githubusercontent.com/4356514/138269695-fac234da-8c1a-4406-9307-343fe34e898a.png)
может получится хотя бы реализовать возможность сбора данных по справочнику онлайн с датой последних изменений в правах?
Очень полезная штука была.
Заранее спасибо за помощь.

**Comment by mishkyn-Mms** [comment]
А можно же перенастроить EGRN-bot , только вводить не кадастровый номер, а адреса по которым нужны кадастры.
То есть (пример):
Город- Санкт-Петербург
район- Центральный
Тип улицы- проспект
Название - Невский 
Дом - 65
Помещение/квартира - 1*Н

Далее парсить вывод данных.

**Comment by VideoSar64** [comment]
там может возникать множество значений. даже не подходящие под нужные, а иногда и две одинаковые строчки с одним кадастром в предлагаемых

**Comment by 0-6-1-7** [comment]
_может получится хотя бы реализовать возможность сбора данных по справочнику онлайн с датой последних изменений в правах?_
Думаю, что да. Есть кое-какие мысли на эту тему. Правда, "интеллектуальный" поиск, который он придумали, выдаёт кучу странных адресов - типа меняет местами дом и квартиру.

 _перенастроить EGRN-bot_
Теоретически - да, но мы не увидим информации о том, есть ли переходы права по этим объектам, или это "пустышки". Плюс там нет поиска по маске. В общем, я даже думать над этим не хочу.

**Comment by VideoSar64** [comment]
А если поиск производить не по адресу, а по кадастровому номеру из файла KN.xls

**Comment by 0-6-1-7** [comment]
Дык бот именно так и работает при заказе выписок. 
А остальную часть работы - поиск КН по адресу и поиск по КН данных о наличии сведений о переходах права - сейчас приходится делать по старинке, руками, тихонечко матерясь словами благодарности в адрес росреестра.

**Comment by VideoSar64** [comment]
я про механизм SIpON headless No Captcha.py
поиск кадастров по помещениям в многоквартирном доме я обошел. правда тоже немного ручками приходится допиливать.
на сайте https://egrp365.org/extra/ выбираю поиск по адресу. Ввожу адрес дома, он выдает списков всего что с этим адресом. Далее в Excel и немного магии. На выходе список необходимых кадастровых номеров.
А вот дальше хотелось бы получать всё тоже что и было при запуске SIpON headless No Captcha.py
![image](https://user-images.githubusercontent.com/4356514/138278265-6f231734-af42-48ad-bd6b-777c4f13ad69.png)

**Comment by 0-6-1-7** [comment]
Эти левые сайты плодятся и дохнут пачками ежемесячно.
Я пока не знаю как автоматизировать получение данных о наличии сведений о переходах прав - нужно время и эксперименты.

**Comment by VideoSar64** [comment]
сайт выше работает уже пару лет. я просто поделился как я стал собирать нужный перечень кадастровых номеров. пока тоже эксперементирую с возможностями как получить данные из справочника. но познаний в python не хватает)

**Comment by 0-6-1-7** [comment]
К сожалению, я так и не смог ничего найти по адресу - всё ломается с таймаутом.
Чисто в теории - у росреестра есть REST API, и я даже делал для него скрипты. Быстродействие колоссальное, и процесс очень простой. Жаль только, что через API видно только часть базы росреестра, т.е. многих адресов вообще нет. И сведений о переходах прав тоже нет.

**Comment by 0-6-1-7** [comment]
Ну, есть две новости: хорошая и плохая.
Плохая - всё не так хорошо, как хотелось бы. Хорошая - всё не так плохо, как могло бы быть.
SIpON v3 alfa
В первом приближении - оно работает.

**Comment by VideoSar64** [comment]
> Ну, есть две новости: хорошая и плохая. Плохая - всё не так хорошо, как хотелось бы. Хорошая - всё не так плохо, как могло бы быть. SIpON v3 alfa В первом приближении - оно работает.

работает. браво. 
единственное уточнение. можно в площади заменить точку на запятую? а то при площади например 5.7 ставит в ячейку дату(

**Comment by 0-6-1-7** [comment]
> > Ну, есть две новости: хорошая и плохая. Плохая - всё не так хорошо, как хотелось бы. Хорошая - всё не так плохо, как могло бы быть. SIpON v3 alfa В первом приближении - оно работает.
> 
> работает. браво. единственное уточнение. можно в площади заменить точку на запятую? а то при площади например 5.7 ставит в ячейку дату(

Пробуйте.

**Comment by volgogradetc** [comment]
Интересно как отреагирует Росреестр на массовые запросы.

**Comment by VideoSar64** [comment]
> > > Ну, есть две новости: хорошая и плохая. Плохая - всё не так хорошо, как хотелось бы. Хорошая - всё не так плохо, как могло бы быть. SIpON v3 alfa В первом приближении - оно работает.
> > 
> > 
> > работает. браво. единственное уточнение. можно в площади заменить точку на запятую? а то при площади например 5.7 ставит в ячейку дату(
> 
> Пробуйте.

![image](https://user-images.githubusercontent.com/4356514/139047922-9ba23f60-af0f-4d0f-8d6d-d62cfbcdf0d0.png)

**Comment by 0-6-1-7** [comment]
Ок, проверю. 
На самом деле, авторизация в ЛК вообще не нужна - то ли глюк разработчиков, то ли фича: капчу достаточно ввести всего один раз, потом можно хоть целый день проверять КН.
Ближайшие два дня заняты, на выходных сделаю рабочий вариант.

**Comment by VideoSar64** [comment]
Спасибо. Фичу с капчей тоже заметил.

**Comment by VideoSar64** [comment]
Ой как не вовремя сейчас надо 1500 КН проверить 🥲
Ручками пока придётся. 
Не могу понять что они поменяли что код перестал работать. Какой то элемент поменяли что ли в странице. Или тайм-аут надо где то поставить.

**Comment by VideoSar64** [comment]
> Ок, проверю. На самом деле, авторизация в ЛК вообще не нужна - то ли глюк разработчиков, то ли фича: капчу достаточно ввести всего один раз, потом можно хоть целый день проверять КН. Ближайшие два дня заняты, на выходных сделаю рабочий вариант.

Удалось победить трехглавого Росреестра?

**Comment by 0-6-1-7** [comment]
Пока разгребаю завал на основной работе, через пару часов начну заниматься росреестром.

**Comment by VideoSar64** [comment]
что уже только не пробовал. никак не выходит. не могу вычислить какой элемент ищет, что не находит и выдает ошибку получения данных

**Comment by 0-6-1-7** [comment]
Спокойствие! Только спокойствие! Я работаю. Завтра будет рабочий вариант.

**Comment by 0-6-1-7** [comment]
Готово, проверяйте.

**Comment by VideoSar64** [comment]
> Готово, проверяйте.

я так понял многое пришлось поменять, но у меня ругается на то что Chrome уже запущен(

**Comment by VideoSar64** [comment]
поработал и перестал
![image](https://user-images.githubusercontent.com/4356514/139571965-913680e1-5f30-4a51-b3aa-9d586fb24625.png)

**Comment by VideoSar64** [comment]
> поработал и перестал
> ![image](https://user-images.githubusercontent.com/4356514/139571965-913680e1-5f30-4a51-b3aa-9d586fb24625.png)
> 

Это не ошибка. Это баг
Как только натыкается на кадастровый номер который относится к "сооружению" сразу стоп. Видимо информация по таким кадастрам имеет другую структуру.

**Comment by 0-6-1-7** [comment]
У этого объекта нет характеристики "Площадь", вместо него "протяженность". Я с таким не сталкивался и не знаю как эту ситуацию обработать.
Если нужно куда-то записывать - например, в отдельную колонку "Характеристика", это можно организовать. Либо просто пропускать и оставлять в колонке "Площадь" пустое место.

**Comment by VideoSar64** [comment]
> У этого объекта нет характеристики "Площадь", вместо него "протяженность". Я с таким не сталкивался и не знаю как эту ситуацию обработать.
> Если нужно куда-то записывать - например, в отдельную колонку "Характеристика", это можно организовать. Либо просто пропускать и оставлять в колонке "Площадь" пустое место.

Второй вариант предпочтительнее. 
Эти кадастры в дальнейшем анализе не нужны. Но хотелось бы понимать что он отработан и это сооружение. А не ошибка получения данных. 
И не хватает конечно фонового режима работы. 
Приходится ждать окончания работы скрипта.

**Comment by 0-6-1-7** [comment]
Готово.
Записывается "Не указано для этого ОН или ошибка"
И ещё есть ошибка - если с первого же КН возникла ошибка капчи, этот КН помечается как ошибка. Исправлю, но уже не сегодня.

**Comment by 0-6-1-7** [comment]
Эм.. насчёт фонового режима - запускать из проводника дабл-кликом. После ввода капчи и "Обработка файла" можно всё свернуть - оно как раз в фоне и будет работать.
Можно, конечно, при ошибке поднимать окно, но я не уверен, что выпрыгнувшее в неподходящий момент окно - хороший вариант. Можно, пожалуй, сделать уведомление в трее, раз уж основная часть почти работает...

**Comment by 0-6-1-7** [comment]
Обновил.
Чуть подправил интерфейс и немного изменил обработку странной ситуации, когда сайт перестаёт нормально реагировать на введённый в поле поиска КН.

**Comment by VideoSar64** [comment]
> Обновил. Чуть подправил интерфейс и немного изменил обработку странной ситуации, когда сайт перестаёт нормально реагировать на введённый в поле поиска КН.

работает. Огромное спасибо. Спасибо  что поддержали в сложное время. И не бросили идею.

**Comment by volgogradetc** [comment]
Спасибо большое!  В v.2 добавлял выгрузку номер права вместе с датой.(полезно для проведения общих собраний).  (в итоге ограничения и права сыпались в одну ячейку и я потом в Экселе разгребал).

**Comment by 0-6-1-7** [comment]
Я иногда подумываю, а не сохранять ли номер права, но пока не придумал как это визуализировать. По одному объекту может быть 20-30 строк с рег. номерами, в т.ч. как с датами, так и без дат. Если дадите идею как это всё сохранять, я сделаю. Самый простой вариант - в отдельную колонку в одну ячейку все записи.
Вот пример длинного списка 34:35:030110:8605
![image](https://user-images.githubusercontent.com/60964734/139600915-286eaf86-762f-41b5-82b6-86a3b80e3c67.png)

**Comment by volgogradetc** [comment]
Я думаю разгребать нет смысла . Меня беспорядок в этой ячейке не пугает.

**Comment by VideoSar64** [comment]
> Я иногда подумываю, а не сохранять ли номер права, но пока не придумал как это визуализировать. По одному объекту может быть 20-30 строк с рег. номерами, в т.ч. как с датами, так и без дат. Если дадите идею как это всё сохранять, я сделаю. Самый простой вариант - в отдельную колонку в одну ячейку все записи. Вот пример длинного списка 34:35:030110:8605 ![image](https://user-images.githubusercontent.com/60964734/139600915-286eaf86-762f-41b5-82b6-86a3b80e3c67.png)

78:14:0007553:12240
Вот пример когда на помещение 109 прав собственности. 
Да и потом просто право собственности без ФИО так себе информация для заполнения бланков решения собственников. ФИО только через запрос в ФГИС получить можно.

**Comment by volgogradetc** [comment]
Согласен, но бывает полезной.
Работает отлично.
Вот кстати за 2 часа работы:
![Пример](https://user-images.githubusercontent.com/65552927/139633477-eb2b29b8-1c46-47e6-8f58-28d7b0b7f1bb.png)

**Comment by 0-6-1-7** [comment]
Ахаха я лошара. Как интересно читать документация после того как разбил лоб.
Сейчас переделаю, будет по 10 штук сразу искать, должно быть побыстрее.
Хотя и 200+ штук за приемлемое время находится, но мне лень по страничкам щёлкать.
![image](https://user-images.githubusercontent.com/60964734/139727286-1f370c33-42fd-4af9-91ed-1b518b0e4104.png)

**Comment by 0-6-1-7** [comment]
Пакетами по 10 существенно быстрее.
"КН найден, но не отображается" - сайт за 20 секунд не отобразил результат. Можно ещё увеличить таймаут, но быстрее просто кнопку нажать для перезапуска.
Завтра выложу в общий доступ.
![image](https://user-images.githubusercontent.com/60964734/139776804-1e4caaf9-e7f5-4b63-ab6e-fe4f996d699e.png)

**Comment by 0-6-1-7** [comment]
Версия 3.2. в папке SIpON v3 alfa
