### ISSUE TITLE
Ошибка пакетной обработки

### ISSUE THREAD

**Issue by VideoSar64** [0-6-1-7/rosreestr#8]
Ошибка при пакетной обработке (v3.2)
Тот же файл при запуске 3.1 без ошибок 
![image](https://user-images.githubusercontent.com/4356514/139841251-8efb9a8e-2e4b-4502-ae6f-fc916b330c2e.png)

**Comment by 0-6-1-7** [comment]
На одном файле или кадастровом номере или на разных непредсказуемых? Я на двух компах прогнал больше 2 тысяч КН без ошибок.
![image](https://user-images.githubusercontent.com/60964734/139912475-2105f119-6528-474f-a19c-a07e3c46e922.png)

**Comment by 0-6-1-7** [comment]
А, стопэ! Обновите библиотеку gatherInfo2.py - такая ошибка на старой версии выскакивала, я её уже исправил.

**Comment by VideoSar64** [comment]
ошибка сохраняется
Вот файл
https://yadi.sk/i/1hH1tMUTZ-fvXA

**Comment by 0-6-1-7** [comment]
Перевыложил полностью рабочий комплект.
Дважды прогнал ваш файл - первый раз файл обработался полностью за 998 секунд, второй - за 875
https://disk.yandex.ru/i/PhwT0nMly78yBg
![image](https://user-images.githubusercontent.com/60964734/139924947-51d0e9b8-001f-44b6-82ca-21c490386164.png)

Прошу прощения за доставленные неудобства.

**Comment by VideoSar64** [comment]
это вы простите за назойливость. теперь всё работает четко. можно подумать и о красоте. 
кстати площадь снова с точкой. есть сложности в дальнейшей работе с файлом. приходится автозамену делать с точки на запятую в дробных площадях
Спасибо за оперативность

**Comment by 0-6-1-7** [comment]
Исправил площадь.
Чуть почистил код.
Добавил скрипт для поиска КН по адресам.

**Comment by volgogradetc** [comment]
Работает, примерно 1 секунда на 1 объект

**Comment by 0-6-1-7** [comment]
Доступна версия 4

Почему сразу 4 после 3 альфа:
- полностью переписал алгоритмы взаимодействия с сайтом, что привело к почти полному переписыванию кода;
- оба варианта поиска (по кадастровому номеру и по адресу) объединены в одну программу;
- поиск по адресу сразу же выбирает данные по найденным объектам;
- поиск по КН выполняется пакетами по 50 штук, в результате средняя скорость достигает 5-7 тысяч КН в час.
